package com.groupdocs.examples.merger;

import java.nio.file.Path;

import static com.groupdocs.examples.merger.utils.FilesUtils.makeFilesPath;

public interface SampleFiles {
    Path SAMPLE_DOCX = makeFilesPath("WordProcessing/sample.docx");
    Path SAMPLE2_DOCX = makeFilesPath("WordProcessing/sample2.docx");
    Path SAMPLE3_DOCX = makeFilesPath("WordProcessing/sample3.docx");
    Path SAMPLE4_DOCX = makeFilesPath("WordProcessing/sample4.docx");
    Path SAMPLE_XLSX = makeFilesPath("Spreadsheet/sample.xlsx");
    Path SAMPLE_VSDX = makeFilesPath("Diagram/sample.vsdx");
    Path SAMPLE_DOCX_10_PAGES = makeFilesPath("WordProcessing/sample-10-pages.docx");
    Path SAMPLE_SIMPLE_PDF = makeFilesPath("Pdf/sample_simple.pdf");
    Path SAMPLE_EMF = makeFilesPath("Image/sample.emf");
    Path SAMPLE_PPTX = makeFilesPath("Presentation/sample.pptx");
    Path SAMPLE_PDF = makeFilesPath("Pdf/sample.pdf");
    Path SAMPLE_TXT = makeFilesPath("Text/sample.txt");
    Path SAMPLE_JPG = makeFilesPath("Image/sample5.jpg");
    Path SAMPLE_SVG = makeFilesPath("Image/sample_SVG.svg");
    Path SAMPLE_PNG = makeFilesPath("Image/sample1.png");
    Path SAMPLE_BMP = makeFilesPath("Image/sample2.bmp");
    Path SAMPLE_PROTECTED_XLSX = makeFilesPath("Spreadsheet/sample_protected.xlsx");
    Path SAMPLE_PROTECTED_DOCX = makeFilesPath("WordProcessing/sample_protected.docx");
    Path SAMPLE_DOC = makeFilesPath("WordProcessing/sample.doc");
    Path SAMPLE_7Z = makeFilesPath("Archive/sample.7z");
    Path SAMPLE_CSV = makeFilesPath("Spreadsheet/sample.csv");
    Path SAMPLE_DOCM = makeFilesPath("WordProcessing/sample.docm");
    Path SAMPLE_DOT = makeFilesPath("WordProcessing/sample.dot");
    Path SAMPLE_DOTM = makeFilesPath("WordProcessing/sample.dotm");
    Path SAMPLE_DOTX = makeFilesPath("WordProcessing/sample.dotx");
    Path SAMPLE_EMZ = makeFilesPath("Image/sample.emz");
    Path SAMPLE_EPUB = makeFilesPath("Ebook/sample.epub");
    Path SAMPLE_HTML = makeFilesPath("Web/sample.html");
    Path SAMPLE_MHT = makeFilesPath("Web/sample.mht");
    Path SAMPLE_MHTML = makeFilesPath("Web/sample.mhtml");
    Path SAMPLE_ODP = makeFilesPath("Presentation/sample.odp");
    Path SAMPLE_ODS = makeFilesPath("Spreadsheet/sample.ods");
    Path SAMPLE_ODT = makeFilesPath("WordProcessing/sample.odt");
    Path SAMPLE_ONE = makeFilesPath("Note/sample.one");
    Path SAMPLE_OTP = makeFilesPath("Presentation/sample.otp");
    Path SAMPLE_OTT = makeFilesPath("WordProcessing/sample.ott");
    Path SAMPLE_PPS = makeFilesPath("Presentation/sample.pps");
    Path SAMPLE_PPSX = makeFilesPath("Presentation/sample.ppsx");
    Path SAMPLE_PPT = makeFilesPath("Presentation/sample.ppt");
    Path SAMPLE_PPTM = makeFilesPath("Presentation/sample.pptm");
    Path SAMPLE_RTF = makeFilesPath("WordProcessing/sample.rtf");
    Path SAMPLE_SVGZ = makeFilesPath("Image/sample_SVGZ.svgz");
    Path SAMPLE_TAR = makeFilesPath("Archive/sample.tar");
    Path SAMPLE_TEX = makeFilesPath("PageDescriptionLanguage/sample.tex");
    Path SAMPLE_TIF = makeFilesPath("Image/sample.tif");
    Path SAMPLE_TIFF = makeFilesPath("Image/sample.tiff");
    Path SAMPLE_TSV = makeFilesPath("Spreadsheet/sample.tsv");
    Path SAMPLE_VDX = makeFilesPath("Diagram/sample.vdx");
    Path SAMPLE_VSDM = makeFilesPath("Diagram/sample.vsdm");
    Path SAMPLE_VSSM = makeFilesPath("Diagram/sample.vssm");
    Path SAMPLE_VSSX = makeFilesPath("Diagram/sample.vssx");
    Path SAMPLE_VSTM = makeFilesPath("Diagram/sample.vstm");
    Path SAMPLE_VSTX = makeFilesPath("Diagram/sample.vstx");
    Path SAMPLE_VSX = makeFilesPath("Diagram/sample.vsx");
    Path SAMPLE_VTX = makeFilesPath("Diagram/sample.vtx");
    Path SAMPLE_WAV = makeFilesPath("Audio/sample.wav");
    Path SAMPLE_XLAM = makeFilesPath("Spreadsheet/sample.xlam");
    Path SAMPLE_XLS = makeFilesPath("Spreadsheet/sample.xls");
    Path SAMPLE_XLSB = makeFilesPath("Spreadsheet/sample.xlsb");
    Path SAMPLE_XLSM = makeFilesPath("Spreadsheet/sample.xlsm");
    Path SAMPLE_XLT = makeFilesPath("Spreadsheet/sample.xlt");
    Path SAMPLE_XLTM = makeFilesPath("Spreadsheet/sample.xltm");
    Path SAMPLE_XLTX = makeFilesPath("Spreadsheet/sample.xltx");
    Path SAMPLE_XPS = makeFilesPath("PageDescriptionLanguage/sample.xps");
    Path SAMPLE_ZIP = makeFilesPath("Archive/sample.zip");
}
